### ISSUE TITLE
Output questions

### ISSUE THREAD

**Issue by informitics** [ssharoff/biberpy#2]
We have a couple of questions concerning the output.  We are attempting to port this to C#.

- What do the numeric values output represent?
- Is there a way to map the headers to their Biber equivalent?  Like E16.Nouns=>NN?

**Comment by ssharoff** [comment]
Thanks for porting this to C#.

1. these are the values of the respective Biber features for a document.
2. E16.Nouns is precisely how (Biber, 1988) refers to these features, the names are taken directly from the long list in the Appendix to that book.

**Comment by informitics** [comment]
Thanks!
